### ISSUE TITLE
Can't hear pronunciations

### ISSUE THREAD

**Issue by JunkMeal** [FreeLanguageTools/vocabsieve#113]
**Describe the bug**

**To Reproduce**
1. get the definition of the german word Chef for example
2. click on pronunctiations -> you can't hear some of them

**Expected behavior**
When I clicked on the pronunciation I wanted to hear it but I didn't.

**Screenshots**
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/65283415/0d0ec132-efbd-4d78-89db-8293c55b0f52)

**Desktop (please complete the following information):**
 - OS: archlinux
- Vocabsieve version (if nightly, must be latest): from aur

**Additional context**
When I added it as a card to my anki deck I could hear it there.
Some pronunciations worked some didn't

**Comment by artjomsR** [comment]
This is already fixed on latest nightly / the fix for this will be applied on the next release. The problem was that some audios would download as .ogg which VocabSieve struggles to play under Windows but plays fine on Anki. On the latest version, you're able to choose the download format (.ogg/.mp3) for all the audios

**Comment by JunkMeal** [comment]
Ok thanks! I am looking foward to a new release.

**Comment by artjomsR** [comment]
You can use the nightly for now, I think it's in a good state https://nightly.link/FreeLanguageTools/vocabsieve/workflows/build-binaries/master
