### ISSUE TITLE
Exception: cannot create note because it is a duplicate 

### ISSUE THREAD

**Issue by kamanlam** [FreeLanguageTools/vocabsieve#176]
Hi there! Thanks for your amazing work that I loved and made good use of. 

<img width="377" alt="Screenshot 2024-10-30 152429" src="https://github.com/user-attachments/assets/a82925f4-3d0a-4eaf-bcb0-d49a77f5ea17">

Unfortunately this error message keeps pooping up, as I tried to

1. updated the windows version
2. tried Kindle import into Anki
3. retried importing to a new deck, still no luck

May I ask if it is a known bug or what should I do?

Thank you in advance for your help.

**Comment by artjomsR** [comment]
Is this the kindle importer? Have you tried selecting the next available date (based on the one that was preselected for you when the importer opens).

I think what's happening is when you do an import, it saves the last import day. Then, next time you open the import window, it uses the same date as a start date for new notes collection. Which means the cards on this day will be attempted to be added twice. Whereas instead, it should collect new cards starting from the next available day

**Comment by 1over137** [comment]
@artjomsR These are intended, and also overlaps are handled in a way that will try to not miss any items since we are only use the date, not timestamp.
This issue in fact due to a change in AnkiConnect. In the past the addNotes command never gives an error (unlike addNote), but now it does. This needs to be handled in the code.
