### ISSUE TITLE
Doesn't support wayland

### ISSUE THREAD

**Issue by Vilhelm-Ian** [FreeLanguageTools/vocabsieve#28]
In wayland the contents of the clipboard don't appear

**Comment by 1over137** [comment]
Is the application running under Wayland directly or XWayland?

**Comment by 1over137** [comment]
I tried testing it on Wayland. As you described the clipboard content doesn't appear. Unfortunately this is due to a restriction on Wayland which does not allow clipboard pasting from unfocused applications. As with Mac, a workaround is now applied to instead check for clipboard content when the window regains focus. This unfortunately breaks the backgrorund single-word lookup feature which doesn't require you to focus the window at all, but I don't know of a better way to fix this.
