### ISSUE TITLE
Duplicate error based on example sentence, not target word

### ISSUE THREAD

**Issue by TheReverseSide** [FreeLanguageTools/vocabsieve#29]
Example sentence: "The dog runs around the house"
I cant add both "dog" and "house" because it will recognize the same sentence and throw an error.

A better solution for duplicates could be checking the target word, instead of the example sentence

**Comment by 1over137** [comment]
Vocabsieve does not check for duplicate notes.
Anki considers two notes to be duplicates when their values for the first field are the same.
I generally suggest using the word as the first field rather than the sentence.
To do this, simply move the word field to the type in Anki's note type settings.

**Comment by TheReverseSide** [comment]
Great, thanks!
