### ISSUE TITLE
Don´t Work windows 10 version 0.8.2

### ISSUE THREAD

**Issue by vczEz** [FreeLanguageTools/vocabsieve#32]
![Screenshot_168](https://user-images.githubusercontent.com/78620977/201543207-4ca651a9-86b4-433a-8785-b31b49f91ce5.png)

**Comment by 1over137** [comment]
@jonahsol 
Can you check if the cx_freeze version works on your machine with the current code?
I probably won't be able to do much in the next ~2 weeks, so if you find a solution, post a binary here.

**Comment by jonahsol** [comment]
Thanks for opening the issue @vczEz, [the v0.8.2 installer](https://github.com/FreeLanguageTools/vocabsieve/releases/tag/v0.8.2) isn't working for me either.

@1over137 I was able to get [a working installer](https://send.zcyph.cc/download/9a0d6000338c4a41/#TvOmvwUKwcev3rdAlvZWFQ) on a Windows machine following the steps in `appveyor.yml`. Instead of using the wheel install `python -m pip install https://freelanguagetools.org/python_lzo-1.12-cp38-cp38-win_amd64.whl"` I used a wheel for the python version installed on my machine (downloaded from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-lzo)). Any ideas on why the Appveyor build isn't working?

**Comment by 1over137** [comment]
It seems to work after I added a `__init__.py` in `.ui`
Not having this causes it to not include the `.ui` subpackage when installing the folder as a python package. Not sure why it works on your machine, though.
