### ISSUE TITLE
The versionv0.9.2 does not works for macos 

### ISSUE THREAD

**Issue by aniespica** [FreeLanguageTools/vocabsieve#51]
**Describe the bug**
When I open the application an error happens with the message: " “vocabsieve” is damaged and can’t be opened. You should move it to the Trash."

**To Reproduce**
1. Go to ['vocabsieve v0.9.2'](https://github.com/FreeLanguageTools/vocabsieve/releases/tag/v0.9.2)
2. download the [vocabsieve-v0.9.2-macos.dmg](https://github.com/FreeLanguageTools/vocabsieve/releases/download/v0.9.2/vocabsieve-v0.9.2-macos.dmg)
3. Open with admin permission 

**Desktop (please complete the following information):**
 - OS: Mac 12.6
- Vocabsieve version (if nightly, must be latest): 0.9.2

**Comment by 1over137** [comment]
It isn't actually damaged. It's just quarantined by Apple due to signature issues, and probably cannot be fixed unless I go pay 100 usd a year for a developer certificate. 
Follow this guide to unquarantine it, and it should work fine.
https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/
