### ISSUE TITLE
Ability to teach lemmatization or definitions

### ISSUE THREAD

**Issue by Mycheze** [FreeLanguageTools/vocabsieve#87]
**Is your feature request related to a problem? Please describe.**
It's very frustrating when a word has a definition, but doesn't get lemmatized properly, especially if I know what it should be. Editing the word is a pain, but sometimes works. But if there was a way to teach the tool your lemmatization, even if just one at a time, would be very nice. And potentially share with future learners. Same goes for definitions. Usually, Czech wiktionary doesn't have the word, but I can figure it out from context or with a different dictionary. But I have no way of teaching vocabsieve that definition.

**Describe the solution you'd like**
When a word doesn't find a definition, allow there to be a way to teach it the proper lemmatization (then check definition again)  and then input your own definition. Then, have the tool save that in some way so that it can be referenced in the future.

**Additional context**

**Comment by 1over137** [comment]
I'm not sure how easy this would be to implement. I think the main limitation to the current lemmatization approach is due to the fact that it cannot use context. To improve on this, either a different lemmatization pipeline needs to be used, or vocabsieve will need to have an internal context-aware lemmatization engine. 

In the future, if the dictionary handling code is revamped into a more flexible system, I can consider implementing some sort of caching as well as a way to fuzzy match, and it might be feasible to implement a way to save the preferred definition for a specific word. I'm not sure how useful that would be though. The nature of Anki is such that you only rarely need to add a second card for each word, so it might not be too useful if the information is not available to other learners.

In the mean time, I think the best way to address this is to complain to the author of the lemmatization library: https://github.com/adbar/simplemma and provide some sources for better lemmatization data you can find.
