### ISSUE TITLE
Clear vocab builder database for books after import

### ISSUE THREAD

**Issue by RasmusRendal** [FreeLanguageTools/vocabsieve#89]
**Is your feature request related to a problem? Please describe.**
My current workflow for importing vocabulary from koreader is as follows:
 * Connect to my koreader device over sshfs
 * Use the "repeat last import", select the books I'm importing vocab from, go to the earliest possible date, and import everything
 * Delete every lookup in the book in koreader

That last step is unnecessary, vocabsieve should know how to do it.
**Describe the solution you'd like**
I'd like for the import dialog to have some option where after importing vocabulary, it just ran `DELETE FROM vocabulary WHERE title_id='some_title';`, after importing the vocabulary from `some_title`.

**Additional context**
It might be a bit of a dangerous feature, writing to the database of other programs. But it's only the vocabulary database, and if I miss mining an important word, I'll just end up mining it another time.

I'd be willing to implement this feature for KoreaderVocabImporter, as that's the device I have access to.

**Comment by 1over137** [comment]
Why do you need this though? Importer is supposed to remember when you last left off and not import too many repeats. The database also doesn't take that much space on the device. Why not just occasionally delete the database?

**Comment by 1over137** [comment]
Vocabsieve cannot detect what sentences have been imported before, but Anki by default does not allow adding duplicate notes, which is what happens if you add the same sentence again (unless you have deleted them). The date selector tries to err on the side of caution (i.e. not accidentally skip cards), so it is inclusive (if you imported in the day of 14th, and read more in the evening, and imported again on the 15th, it will try to add everything from the 14th to avoid missing items). It even selects that date (date of last record added last time) by default so you don't even have to do anything.

**Comment by RasmusRendal** [comment]
I had to disable detecting duplicate notes, because it kept detecting two notes from the same sentence as identical, maybe due to some changes I made to the note type?

I don't know how well the date selector handles it when I keep reconfiguring which language I'm learning, to switch between the two.

But I can see this feature request is reaching [spacebar heating](https://xkcd.com/1172/) levels of specificity, and probably isn't worth the trouble upstreaming, so I'll just close the issue :)

**Comment by RasmusRendal** [comment]
However, if someone else does want this feature, it's implemented here: https://github.com/RasmusRendal/vocabsieve/commit/af8f9fe5b913b1f26bb6c7c05e047bfba72a1984
